name: pdufa-daily-ics

on:
  schedule:
    # Runs daily at 03:20 UTC (~06:20 Asia/Jerusalem)
    - cron: "20 3 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "Calendar Agent/requirements.txt"

      # Preflight: prove the file is where we expect
      - name: Preflight check
        run: |
          pwd
          ls -la
          echo "---- recursive ----"
          ls -R
          echo "---- verify requirements.txt ----"
          test -f "Calendar Agent/requirements.txt" && echo "Found: Calendar Agent/requirements.txt" || (echo "NOT FOUND" && exit 1)

      - name: Install dependencies
        run: pip install -r "Calendar Agent/requirements.txt"

      - name: Build CSVs
        env:
          # Optional: only needed if you use online ticker lookup
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: python "Calendar Agent/src/main.py"

      - name: Commit CSV updates
        run: |
          git config user.name "pdufa-bot"
          git config user.email "pdufa-bot@users.noreply.github.com"
          git add "Calendar Agent/data/pdufa_master.csv" "Calendar Agent/data/blank.csv" "Calendar Agent/data/state.json" || true
          git commit -m "chore: daily PDUFA update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
