name: pdufa-daily-ics

on:
  schedule:
    # Runs daily at 03:20 UTC (~06:20 Asia/Jerusalem)
    - cron: "20 3 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "Calendar Agent/requirements.txt"

      # Optional: quick “start” ping on manual runs
      - name: Notify Telegram (started)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          message: |
            🚀 Manually triggered run started
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Run: #${{ github.run_number }}

      - name: Preflight check
        run: |
          pwd
          ls -la
          echo "---- recursive ----"
          ls -R
          echo "---- verify requirements.txt ----"
          test -f "Calendar Agent/requirements.txt" && echo "Found: Calendar Agent/requirements.txt" || (echo "NOT FOUND" && exit 1)

      - name: Install dependencies
        run: pip install -r "Calendar Agent/requirements.txt"

      - name: Build CSVs
        env:
          # Optional: only needed for online ticker lookup
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: python "Calendar Agent/src/main.py"

      - name: Configure Git author
        run: |
          git config user.name "pdufa-bot"
          git config user.email "pdufa-bot@users.noreply.github.com"

      - name: Commit CSV updates
        run: |
          git add "Calendar Agent/data/pdufa_master.csv" "Calendar Agent/data/blank.csv" "Calendar Agent/data/state.json" || true
          git commit -m "chore: daily PDUFA update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"

      # Rebase onto latest remote main before pushing
      - name: Rebase onto remote main
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Push changes
        run: git push origin HEAD:main

      # --- Telegram notifications ---
      - name: Notify Telegram (success)
        if: ${{ success() }}
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          message: |
            ✅ PDUFA daily job succeeded
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Run: #${{ github.run_number }}
            Commit: ${{ github.sha }}
            Trigger: ${{ github.event_name }}
            Time: ${{ github.run_started_at }}

      - name: Notify Telegram (failure)
        if: ${{ failure() }}
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          message: |
            ❌ PDUFA daily job FAILED
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Run: #${{ github.run_number }}
            Trigger: ${{ github.event_name }}
            Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
