name: pdufa-daily-ics

on:
  schedule:
    # Runs daily at 03:20 UTC (~06:20 Asia/Jerusalem)
    - cron: "20 3 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # All shell `run:` steps execute inside the subfolder with a space in its name
    defaults:
      run:
        working-directory: "Calendar Agent"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "Calendar Agent/requirements.txt"

      # (Optional) sanity check the workspace paths
      - name: Show layout
        run: |
          pwd
          ls -la
          echo "---- recursive ----"
          ls -R

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build CSVs; if the secret isn't set, the script will just skip online lookups
      - name: Build CSVs
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: python src/main.py

      - name: Commit CSV updates
        run: |
          git config user.name "pdufa-bot"
          git config user.email "pdufa-bot@users.noreply.github.com"
          git add data/pdufa_master.csv data/blank.csv data/state.json || true
          git commit -m "chore: daily PDUFA update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
